import argparse
import os

"""

Producing samples:
python scripts/run_fastsim.py --run --output-folder PATH_TO_DATASET/output --n-jobs 100 --starting-job 0

Each job is 50k events. This script produces 100 jobs for each process, and with 11 processes, this makes 1100 jobs
in total. If your slurm system has a limit on the number of jobs you can submit, consider submitting
less jobs at a time (need to specify a smaller --n-jobs and adjust --starting-job for each batch of submissions).

The commands will produce the samples in PATH_TO_DATASET/output0, PATH_TO_DATASET/output1... folders.

"""


parser = argparse.ArgumentParser()
parser.add_argument(
    "--run", action="store_true", help="Run the job after generating it"
)
parser.add_argument("--output-folder", type=str, default="fast_sim/outputs")
parser.add_argument(
    "--n-jobs",
    type=int,
    default=1,
    help="Number of jobs to generate (the number will be appended to the folder for each job)",
)
parser.add_argument(
    "--starting-job",
    type=int,
    default=1,
    help="Starting job number (useful for continuing from a previous run)",
)

parser.add_argument("--events-per-job", type=int, default=None,
                    help="Override Main:numberOfEvents from the process card. Smaller "
                         "jobs lose less work when Delphes' TrkUtil::CovSmear aborts "
                         "mid-run (it kills the process), e.g. --events-per-job 5000.")
parser.add_argument("--mem", type=str, default="10G",
                    help="Memory per job (default 10G). 6-jet jobs have been observed "
                         "at 5.5G peak RSS, so the old 5G was below the peak.")
parser.add_argument("--partition", type=str, default="roma",
                    help="SLURM partition (default roma). atlas is capped at node=1 on "
                         "milano but node=5 on roma, so roma gives 5x the concurrency.")
parser.add_argument("--account", type=str, default="atlas", help="SLURM account")
parser.add_argument("--time-limit", type=str, default="01:00:00",
                    help="SLURM time limit (default 01:00:00; a 5k-event job takes "
                         "~5 min, a 50k-event one up to ~95 min)")
parser.add_argument(
    "--processes",
    nargs="*",
    default=None,
    help="Only generate these processes (dataset names, e.g. p8_ee_ZH_vvqq_ecm240). "
         "Default: all 11.",
)
parser.add_argument("--corrupted-file-list", type=str, default=None, help="Path to the list generated by scripts/find_corrupted_root_files.py. If set, other settings will be ignored.")
args = parser.parse_args()

template = """#!/bin/bash
#SBATCH --partition={partition}          # Specify the partition
#SBATCH --account={account}               # Specify the account
#SBATCH --mem={mem}                      # Memory per job
#SBATCH --cpus-per-task=2                # Request 2 CPU cores
#SBATCH --nodes=1                        # Request 1 node
#SBATCH --time={time_limit}              # Wall-clock limit
#SBATCH --job-name={jobname}             # Name the job
#SBATCH --output=/fs/ddn/sdf/group/atlas/d/gregork/fastsim/log/{jobname}_%j_%x.log           # Redirect stdout to a log file
#SBATCH --error=/fs/ddn/sdf/group/atlas/d/gregork/fastsim/err/{jobname}_%j_%x.err            # Redirect stderr to a log file

# Load the Singularity environment
export APPTAINER_CACHEDIR=/sdf/scratch/atlas/gregork/apptainer_cache
export APPTAINER_TMPDIR=/sdf/scratch/atlas/gregork/apptainer_tmp

{script}

"""

detector_cards = {
    2: "delphes_cards/detector/card_IDEA_N2.tcl",
    4: "delphes_cards/detector/card_IDEA_N4.tcl",
    6: "delphes_cards/detector/card_IDEA_N6.tcl",
}


# Command for generating a physics process. The Pythia card is a parameter
# because each job needs its own copy with a unique Random:seed (see
# write_seeded_pythia_card).
CMD_TEMPLATE = (
    "DelphesPythia8_EDM4HEP {detector_card} delphes_cards/edm4hep_IDEA.tcl "
    "{pythia_card} {out_folder}/{process}.root"
)

process_name_to_cmd = {
    "p8_ee_ZH_6jet_ecm240": "6jet",
    "p8_ee_ZH_vvbb_ecm240": "2jet_ZH",
    "p8_ee_ZH_bbbb_ecm240": "ZH_bbbb",
    "p8_ee_ZH_vvgg_ecm240": "ZH_nunugg",
    "p8_ee_ZH_qqbb_ecm240": "ZH_qqbb",
    "p8_ee_ZH_vvqq_ecm240": "2jet_ZH_nunuqq",
    "p8_ee_ZH_qqgg_ecm240": "ZH_qqgg",
    "p8_ee_ZH_bbgg_ecm240": "ZH_bbgg",
    "p8_ee_ZH_6jet_HF_ecm240": "ZH_6jet_HF",
    "p8_ee_ZH_6jet_LF_ecm240": "ZH_6jet_LF",
    "p8_ee_ZH_qqqq_ecm240": "ZH_qqqq",
}


'''
def find_tree_name(uproot_file, explicit_name: str) -> str:
    if explicit_name:
        return explicit_name if explicit_name in uproot_file else None

    preferred = ["events", "Events", "EventTree", "Delphes"]
    for name in preferred:
        if name in uproot_file:
            return name

    try:
        classnames = uproot_file.classnames()
    except Exception:
        classnames = {}
    for name, classname in classnames.items():
        if classname.startswith("TTree"):
            return name
    return None


def is_corrupted(path):
    try:
        with uproot.open(path) as f:
            tree_name = find_tree_name(f, None)
            if not tree_name:
                return True
            tree = f[tree_name]
            entries = tree.num_entries
            if entries != 50000:
                return True
    except Exception:
        return True
    return False'''

cmds = {cmd: CMD_TEMPLATE for cmd in process_name_to_cmd.values()}

Njets = {
    "6jet": 6,
    "2jet_ZH": 2,
    "ZH_bbbb": 4,
    "ZH_nunugg": 2,
    "ZH_qqbb": 4,
    "2jet_ZH_nunuqq": 2,
    "ZH_qqgg": 4,
    "ZH_bbgg": 4,
    "ZH_6jet_HF": 6,
    "ZH_6jet_LF": 6,
    "ZH_qqqq": 4,
}


def cmd_gen(cmd):
    return f"singularity exec -B /sdf -B /cvmfs -B /fs --nv docker://gkrz/alma:v0 /bin/bash -lc 'source /cvmfs/fcc.cern.ch/sw/latest/setup.sh && {cmd}'"


cmd_to_process = {v: k for k, v in process_name_to_cmd.items()}

# Distinct seed range per process, so job N of two processes never shares a seed.
# Pythia requires 1 <= Random:seed <= 900000000, which leaves room for 900
# processes x 1e6 jobs.
PROCESS_SEED_OFFSET = {
    process: i * 1_000_000 for i, process in enumerate(sorted(process_name_to_cmd))
}


def write_seeded_pythia_card(process, job_index, out_folder, n_events=None):
    """Copy a process' Pythia card next to the output, with a per-job seed.

    Pythia8 defaults to `Random:setSeed = off`, i.e. it always starts from its
    built-in base seed, and none of the cards in delphes_cards/process/ set it.
    Every job therefore ran the identical command on the identical card and
    generated byte-identical events: in IDEA_20260120 all ~650 files of a process
    hold the same 50k events and differ only in the Delphes smearing (which does
    vary, since Delphes' RNG is not seeded from the card either). Gen-level
    distributions there have the statistical power of 50k events, not 32.5M.

    The seed is derived from the job index rather than the clock, so re-running a
    corrupted file reproduces exactly the events it was meant to hold.
    """
    seed = PROCESS_SEED_OFFSET[process] + job_index + 1
    if not 1 <= seed <= 900_000_000:
        raise ValueError(f"seed {seed} out of Pythia's range for job {job_index}")
    src = f"delphes_cards/process/{process}.cmd"
    dst = os.path.abspath(os.path.join(out_folder, f"{process}_seed.cmd"))
    with open(src) as fh:
        body = fh.read().rstrip("\n")
    with open(dst, "w") as fh:
        fh.write(body)
        fh.write(f"\n\n! --- appended by scripts/run_fastsim.py for job {job_index}\n")
        fh.write("Random:setSeed = on\n")
        fh.write(f"Random:seed = {seed}\n")
        if n_events:
            # Pythia takes the last assignment, so this overrides the card value.
            fh.write(f"Main:numberOfEvents = {n_events}\n")
    return dst


import os

if not args.corrupted_file_list:
    os.makedirs(f"{args.output_folder}", exist_ok=True)

    tag = f"{args.events_per_job // 1000}k" if args.events_per_job else "50k"
    selected = set(args.processes) if args.processes else set(process_name_to_cmd)
    unknown = selected - set(process_name_to_cmd)
    if unknown:
        parser.error("Unknown --processes value(s): " + ", ".join(sorted(unknown)))
    # range(start, start + n_jobs) - the old "+ 1" submitted n_jobs + 1 jobs.
    for i in range(args.starting_job, args.starting_job + args.n_jobs):
        for cmd in cmds:
            process = cmd_to_process[cmd]
            if process not in selected:
                continue
            # Make the folder if it doesn't exist
            out_folder = f"{args.output_folder}{i}"
            os.makedirs(out_folder, exist_ok=True)
            n_jets = Njets[cmd]
            t = template.format(
                script=cmd_gen(
                    cmds[cmd].format(
                        detector_card=detector_cards[n_jets], out_folder=out_folder,
                        process=process,
                        pythia_card=write_seeded_pythia_card(
                            process, i, out_folder, args.events_per_job),
                    )
                ),
                jobname=cmd + "_" + tag + "_" + str(i),
                mem=args.mem,
                partition=args.partition,
                account=args.account,
                time_limit=args.time_limit,
            )
            filename = f"jobs/{cmd}_{tag}_{i}.sh"
            with open(filename, "w") as f:
                f.write(t)
            print(f"Generated {filename}")
            if args.run:
                import os
                os.system(f"sbatch {filename}")
                print(f"Submitted {filename} to slurm")
else:
    # read the corrupted file list line by line and save it
    corrupted_files = []
    with open(args.corrupted_file_list, "r") as f:
        for line in f:
            corrupted_files.append(line.strip().split("\t")[0])
    print(f"Re-running {len(corrupted_files)} corrupted files.")
    for path in corrupted_files:
        # extract the job number from the path
        parts = path.split("/")
        out_folder = "/".join(parts[:-1])
        filename = parts[-1]
        job_number = out_folder.split("output")[-1]
        #
        process_name = filename.split(".root")[0]
        cmd_key = process_name_to_cmd[process_name]
        n_jets = Njets[cmd_key]
        t = template.format(
            script=cmd_gen(
                cmds[cmd_key].format(
                    detector_card=detector_cards[n_jets], out_folder=out_folder,
                    process=process_name,
                    # Same job index -> same seed, so the rerun reproduces the
                    # events the corrupted file was meant to contain.
                    pythia_card=write_seeded_pythia_card(
                        process_name, int(job_number), out_folder,
                        args.events_per_job),
                )
            ),
            jobname=cmd_key + "_50k_rerun_" + str(job_number),
            mem=args.mem,
            partition=args.partition,
            account=args.account,
            time_limit=args.time_limit,
        )
        rerun_filename = f"jobs/{cmd_key}_50k_rerun_{job_number}.sh"
        with open(rerun_filename, "w") as f:
            f.write(t)
        print(f"Generated {rerun_filename} for {path}")
        # delete the file if it exists
        if os.path.exists(path):
            os.remove(path)
            print(f"Deleted corrupted file {path}")
        if args.run:
            import os
            os.system(f"sbatch {rerun_filename}")
            print(f"Submitted {rerun_filename} to slurm")

